### ISSUE TITLE
a bunch of forward slashes

### ISSUE THREAD

**Issue by RowanKaag** [inket/terminal-setup#2]
Any clue why this is happening? I'm not too familiar with Bash

![schermafbeelding 2015-11-23 om 14 59 57](https://cloud.githubusercontent.com/assets/6907625/11338188/f47e2fec-91f2-11e5-8a5a-19d36b409ea5.png)

**Comment by inket** [comment]
Because you're using `zsh` ? I am using the default `bash` so it would be different for you.

**Comment by RowanKaag** [comment]
Fixed:

```
red=$(tput setaf 1)
yellow=$(tput setaf 3)
white=$(tput setaf 7)
export PS1="$red%/% $yellow > $white"
```

**Comment by inket** [comment]
Thanks!
